name: Sid Shanker's Journal
description: Read on to find out what I've been up to and what I've been working on! For my more polished posts, check out http://squidarth.com
meta_description: "Read on to find out what I've been up to and what I've been working on!"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://misc.squidarth.com'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://misc.squidarth.com'
author:         'Sid Shanker'
